config = {'train_data_path':['/gdrive/My Drive/EDITABLE-LUNA16/subset0/',
                             '/gdrive/My Drive/EDITABLE-LUNA16/subset1/',
                             '/gdrive/My Drive/EDITABLE-LUNA16/subset2/',
                             '/gdrive/My Drive/EDITABLE-LUNA16/subset3/',
                             '/gdrive/My Drive/EDITABLE-LUNA16/subset4/',
                             '/gdrive/My Drive/EDITABLE-LUNA16/subset5/',
                             '/gdrive/My Drive/EDITABLE-LUNA16/subset6/',
                             '/gdrive/My Drive/EDITABLE-LUNA16/subset7/',
                             '/gdrive/My Drive/EDITABLE-LUNA16/subset8/'],
          'val_data_path':['/gdrive/My Drive/EDITABLE-LUNA16/subset9/'], 
          'test_data_path':['/gdrive/My Drive/EDITABLE-LUNA16/subset9/'], 
          
          'train_preprocess_result_path':'/gdrive/My Drive/PREPROCESS-LUNA16/', # contains numpy for the data and label, which is generated by prepare.py
          'val_preprocess_result_path':'/gdrive/My Drive/PREPROCESS-LUNA16/',  # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path':'/gdrive/My Drive/PREPROCESS-LUNA16/',
          
          'train_annos_path':'/gdrive/My Drive/EDITABLE-LUNA16/luna16/CSVFILES/annotations.csv',
          'val_annos_path':'/gdrive/My Drive/EDITABLE-LUNA16/luna16/CSVFILES/annotations.csv',
          'test_annos_path':'/gdrive/My Drive/EDITABLE-LUNA16/luna16/CSVFILES/annotations.csv',

          'black_list':[],
          
          'preprocessing_backend':'python',
         } 
